GET {{host}}/api/public/products?id=22
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?favorite=true&limit=15
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?id=22&category=true&limit=15&order=RAND
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?limit=5&page=4
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?categoryName=Alimentos
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?productName=Cacao 10
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "sku": "13213",
  "name": "Cacao 20",
  "description_short": "Hola",
  "description_one": "Hola 1",
  "description_two": "Hola 2",
  "preparation": "Prepa",
  "quantity": 2,
  "user_id": "1",
  "regular_price": "100"
}

###

PUT {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "17",
  "sku": "17",
  "name": "13456",
  "description_short": "Valencia",
  "description_one": "04125456465",
  "description_two": "Administrador",
  "preparation": "Administrador",
  "regular_price": "Administrador",
  "quantity": "Administrador",
  "user_id": "Administrador"
}

###

DELETE {{host}}/api/products/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idproducts": "1"
}

###
