GET {{host}}/api/public/products?id=22
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?favorite=true&limit=15
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?id=22&category=true&limit=15&order=RAND
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?limit=5&page=4
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?categoryName=Alimentos
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products?productName=Cacao 18
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/products
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "sku": "13213",
  "name": "Cacao 10",
  "description_short": "Description short",
  "description_one": "Description long 1",
  "description_two": "Description long 2",
  "preparation": "Preparation",
  "nutrition": "Preparation",
  "quantity": 2,
  "user_id": "1",
  "regular_price": "100"
}

###

PUT {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "2",
  "sku": "13213",
  "name": "Cacao 20",
  "description_short": "Description short",
  "description_one": "Description long 1",
  "description_two": "Description long 2",
  "preparation": "Preparation",
  "nutrition": "Preparation",
  "quantity": 2,
  "user_id": "1",
  "regular_price": "100"
}

###

DELETE {{host}}/api/products/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idproducts": "1"
}

###
