GET {{host}}/api/public/transaction/getID/1
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/public/transaction/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/transactions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "code": 1,
  "processor": "American Express",
  "processor_trans_id": 1,
  "cc_num": "23",
  "cc_type": "123",
  "start_date": "2019-05-01",
  "end_date": "2019-05-15",
  "cart_id": "1",
  "user_id": "2",
  "total": 2700,
  "subtotal": 2700
}

###

PUT {{host}}/api/transaction
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "",
  "code": 1,
  "processor": "Amazon",
  "processor_trans_id": 1,
  "cc_num": "121",
  "cc_type": "211",
  "start_date": "2019-05-15",
  "end_date": "2019-05-23",
  "user_id": "",
  "total": 2700,
  "subtotal": 2700
}

###

DELETE {{host}}/api/transaction
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "1"
}

###
