GET {{host}}/api/public/object/getID/1
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/public/object/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/admin/object/register
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Category test
--WebAppBoundary
Content-Disposition: form-data; name="service_idservice"
Content-Type: text/plain

3
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="fuki.jpeg"
Content-Type: image/jpeg

< ./../image/fuki.jpeg
--WebAppBoundary--

###

POST {{host}}/api/admin/object/update
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="idobject"
Content-Type: text/plain

1

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Category test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="fuki.jpeg"
Content-Type: image/jpeg

< ./../image/fuki.jpeg
--WebAppBoundary--
###

DELETE {{host}}/api/admin/object/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idobject": "1"
}
###
