POST {{host}}/api/public/users/login
Content-Type: application/json

{
  "email": "goa@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.data.token); %}

###

GET {{host}}/api/users
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/src/uploads/7738d966b6fb7811.jpeg
Accept: application/json

###

GET {{host}}/api/public/endpoints
Accept: application/json

###

GET {{host}}/api/users/profile/3
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/public/users/register
Content-Type: application/json

{
  "id": "",
  "email": "pedro@gmail.com",
  "first_name": "Pedro",
  "last_name": "Rodriguez",
  "password": "12345678",
  "address": "Calle Santa Rita",
  "phone": "4164318061",
  "city": "Maracay",
  "state": "Aragua",
  "country": "Venezuela",
  "country_code": "",
  "postal_code": "2120",
  "role_id": 2
}

###

PUT {{host}}/api/users/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usersid": "17",
  "password": "13456",
  "street": "Valencia",
  "phone": "04125456465",
  "role_id": 2
}

###

PUT {{host}}/api/users/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "user_id": "1",
  "email": "ivans10@gmail.com",
  "first_name": "Ivans",
  "last_name": "Del Pino",
  "password": "123456",
  "address": "Santa Rita",
  "phone": "04165646545",
  "active": "1",
  "role_id": "1",
  "inserted_at": "2019-05-07 11:57:09",
  "updated_at": "2019-05-07 11:57:09",
  "id": "1",
  "name": "Administrador",
  "newPassword": "123456"
}

###

DELETE {{host}}/api/users/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usersid": "1"
}

###
