POST {{host}}/api/public/users/login
Content-Type: application/json

{
  "email": "Ivans10@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.data.token); %}

###

GET {{host}}/api/users
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/src/uploads/7738d966b6fb7811.jpeg
Accept: application/json
###

GET {{host}}/api/public/endpoints
Accept: application/json
###

GET {{host}}/api/users/profile/3
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/public/users/register
Content-Type: application/json

{
  "name": "Ivans",
  "password": "123456",
  "email": "Ivans10@gmail.com",
  "street": "Maracay",
  "phone": "04125456465",
  "type": "Administrador"
}
###

PUT {{host}}/api/users/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usersid": "17",
  "password": "13456",
  "street": "Valencia",
  "phone": "04125456465",
  "type": "Administrador"
}
###

DELETE {{host}}/api/users/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usersid": "1"
}
###
