GET {{host}}/api/images/getID/4
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/images/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/images/getStatus/Todo
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/images/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "object_idobject": "2",
  "order_idorder": "5"
}
###

PUT {{host}}/api/admin/images/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idimages": "3",
  "object_idobject": "2",
  "order_idorder": "5"
}
###

DELETE {{host}}/api/images/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idimages": "3"
}
###
