GET {{host}}/api/order/getID/4
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/order/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/order/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "origin_order": "Maracay",
  "destination_order": "Valencia",
  "maximum_delivery_date": "2019/03/18",
  "maximum_withdrawal_date": "2019/03/28",
  "message": "Hola",
  "price": "20154",
  "date_created": "2019/03/18",
  "user_iduser": "1"
}
###

PUT {{host}}/api/admin/order/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idorder": "4",
  "origin_order": "Maracay 2",
  "destination_order": "Valencia 2",
  "maximum_delivery_date": "2019/03/18",
  "maximum_withdrawal_date": "2019/03/28",
  "message": "Hola 2",
  "price": "201542",
  "date_created": "2019/03/18",
  "user_iduser": "1"
}
###

DELETE {{host}}/api/order/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idorder": "4"
}
###
