GET {{host}}/api/payment/getID/4
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/payment/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/payment/register
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Category test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="fuki.jpeg"
Content-Type: image/jpeg

< ./../image/fuki.jpeg
--WebAppBoundary--

###

POST {{host}}/api/admin/payment/update
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="idpayment"
Content-Type: text/plain

1

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Category test
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="fuki.jpeg"
Content-Type: image/jpeg

< ./../image/fuki.jpeg
--WebAppBoundary--

###

DELETE {{host}}/api/payment/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idpayment": "4"
}
###
