GET {{host}}/api/products?id=1
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{host}}/api/products?order=DESC
Accept: application/json
Authorization: Bearer {{auth_token}}

###

POST {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "sku": "17",
  "name": "13456",
  "description_short": "Valencia",
  "description_one": "Hola 11",
  "description_two": "Hola 22",
  "preparation": "preparación",
  "regular_price": "321312",
  "quantity": "23",
  "user_id": "1"
}

###

PUT {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "17",
  "sku": "17",
  "name": "13456",
  "description_short": "Valencia",
  "description_one": "04125456465",
  "description_two": "Administrador",
  "preparation": "Administrador",
  "regular_price": "Administrador",
  "quantity": "Administrador",
  "user_id": "Administrador"
}

###

DELETE {{host}}/api/products/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idproducts": "1"
}

###
