GET {{host}}/api/transportservice/getID/4
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/transportservice/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/transportservice/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name_service": "Maracay",
  "size": "12m",
  "distance": "12Km",
  "weight": "20kg",
  "prom_price": "2000$",
  "transport_idtransport": "2"
}
###

PUT {{host}}/api/transportservice/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport_service": "4",
  "name_service": "Maracay",
  "size": "Valencia",
  "distance": "2019/03/18",
  "weight": "2019/03/28",
  "date_created": "Hola",
  "prom_price": "20154",
  "transport_idtransport": "2019/03/18"
}
###

DELETE {{host}}/api/transportservice/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport_service": "4"
}
###
