GET {{host}}/api/admin/transport/getID/10
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/admin/transport/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}
###

POST {{host}}/api/public/transport/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name_truck": "Henry",
  "user_iduser": "3"
}
###

PUT {{host}}/api/transport/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport": "3",
  "name_truck": "Ivans",
  "user_iduser": "5"
}
###

DELETE {{host}}/api/transport/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "idtransport": "3"
}
###
