POST {{host}}/api/public/user/login
Content-Type: application/json

{
  "email": "desarrollo.theroom@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.data.token); %}
###

GET {{host}}/api/public/endpoints
Accept: application/json
###

GET {{host}}/api/admin/user/getAll/2
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/user/profile/3
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/admin/user/typeuser/cliente
Accept: application/json
Authorization: Bearer {{auth_token}}
###

GET {{host}}/api/public/user/forgot/ivans10@gmail.com
Accept: application/json
###

POST {{host}}/api/public/user/register
Content-Type: application/json

{
  "name": "ivans21",
  "person_name": "Ivans",
  "person_last_name": "Del Pino",
  "password": "123456",
  "phone": "04164318061",
  "street": "Calle Santa Rita",
  "email": "ivans21@gmail.com",
  "type": "Cliente"
}
###

PUT {{host}}/api/user/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userid": "1",
  "password": "123456",
  "street": "Valencia 2",
  "phone": "04125456465",
  "type": "Administrador"
}
###

PUT {{host}}/api/user/updatePassword
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "iduser": "7",
  "name": "Ivans11",
  "password": "123456",
  "email": "Ivans11@gmail.com",
  "street": "Maracay",
  "phone": "04125456465",
  "type": "Administrador",
  "active": "1",
  "date_created": "2019-03-28",
  "newPassword": "1234567"
}
###

DELETE {{host}}/api/user/delete
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "userid": "3"
}
###
